from eepsheet import EepSheet

class EepCombinedSheet(EepSheet):
	COL_REGION = 0
	COL_LOCATION = 1
	COL_SCHOOL = 2
	COL_STUDENT_NAME = 3
	COL_SEX = 4
	COL_GRADUATION_YEAR = 5
	COL_STUDENT_DONOR_ID = 6
	COL_STUDENT_DONOR_NAME = 7
	COL_STUDENT_DONOR_DONATION_AMOUNT_LOCAL = 8
	COL_COMMENT = 9
	COL_IMPORT_ORDER_NUMBER = 10
	COL_AUTO_STUDENT_NUMBER = 11
	COL_AUTO_DONOR_STUDENT_COUNT_NUMBER = 12
	COL_SCHOOL_NAME_LENGTH = 13
